markdown: kramdown

plugins:
 - jekyll-multiple-languages-plugin
 - jekyll-liquify

languages: ["en"]

exclude_from_localizations: ["js", "img", "css", "fonts", "CNAME","scripts","marketing","TRANSLATIONS.md"]

coin: "Masari"

social:
  discord:
    name: "Discord"
    url: "https://discordapp.com/invite/sMCwMqs"
  telegram:
    name: "Telegram" 
    url: "https://t.me/masaricurrency"
  reddit:
    name: "Reddit"
    url: "https://www.reddit.com/r/masari/"
  twitter:
    name: "Twitter"
    url: "https://twitter.com/masaricurrency"
  bitcointalk:
    name: "Bitcoin Talk"
    url: "https://bitcointalk.org/index.php?topic=2159114"